services:
  giropops-senhas:
    build: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
    volumes:
      - strigus:/strigus
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:5000"]  
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
          

  redis:
    image: redis
    networks:
      - giropops
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
        
networks:
  giropops:
    driver: bridge

volumes:
  strigus:
