services:
  giropops-senhas:
    build: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - giropops

networks:
  giropops:
    driver: bridge
